name: Build and push the docker image to ghcr lms staging
on:
  push:
    branches: ["main", "staging"]

jobs:
  build-push:
    environment:
      name: ${{ github.ref_name }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        name: Checking out code

      - name: "Create .env file"
        run: |
          touch .env
          echo VITE_ENV=${{ github.ref_name }} >> .env
          echo VITE_SENTRY_DSN=${{ vars.SENTRY_DSN }} >> .env
          echo VITE_FIREBASE_API_KEY=${{ vars.FIREBASE_API_KEY }} >> .env
          echo VITE_FIREBASE_AUTH_DOMAIN=${{ vars.FIREBASE_AUTH_DOMAIN }} >> .env
          echo VITE_FIREBASE_PROJECT_ID=${{ vars.FIREBASE_PROJECT_ID }} >> .env
          echo VITE_FIREBASE_STORAGE_BUCKET=${{ vars.FIREBASE_STORAGE_BUCKET }} >> .env
          echo VITE_FIREBASE_MESSAGING_SENDER_ID=${{ vars.FIREBASE_MESSAGING_SENDER_ID }} >> .env
          echo VITE_FIREBASE_APP_ID=${{ vars.FIREBASE_APP_ID }} >> .env
          echo VITE_FIREBASE_MEASUREMENT_ID=${{ vars.FIREBASE_MEASUREMENT_ID }} >> .env
          echo VITE_LMS_BASE_URL=${{ vars.LMS_BASE_URL }} >> .env
          echo VITE_GOOGLE_SHEET_BUG_REPORT_URL=${{ vars.GOOGLE_SHEET_BUG_REPORT_URL }} >> .env

      - name: Build the Docker image
        run: eval `ssh-agent -s` && ssh-add ~/.ssh/id_rsa && DOCKER_BUILDKIT=1 docker build --build-arg ENV_FILE=.env -t ghcr.io/blendnet-ai/lms-frontend-${{ github.ref_name }} .

      - name: Push the Docker image to ghcr
        run: docker push ghcr.io/blendnet-ai/lms-frontend-${{ github.ref_name }}:latest
