name: Build and push the docker image to ghcr
on:
  push:
    branches: ["saksham"]

env:
  BACKEND_BASE_URL: ${{ secrets.BACKEND_BASE_URL }}
  BACKEND_WEBSOCKET_URL: ${{ secrets.BACKEND_WEBSOCKET_URL }}
  NEW_FLOW: ${{ secrets.NEW_FLOW }}
  ENV: ${{ secrets.ENV }}
  FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
  CV_BUILDER_URL: ${{ secrets.CV_BUILDER_URL }}
  GOOGLE_SHEETS_URL: ${{ secrets.GOOGLE_SHEETS_URL }}

jobs:
  build-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        name: Checking out code

      - name: "Create .env file"
        run: |
          touch .env
          echo BACKEND_BASE_URL=$BACKEND_BASE_URL >> .env
          echo BACKEND_WEBSOCKET_URL=$BACKEND_WEBSOCKET_URL >> .env
          echo NEW_FLOW=$NEW_FLOW >> .env
          echo ENV=$ENV >> .env
          echo FRONTEND_URL=$FRONTEND_URL >> .env
          echo CV_BUILDER_URL=$CV_BUILDER_URL >> .env
          echo GOOGLE_SHEETS_URL=$GOOGLE_SHEETS_URL >> .env

      - name: Build the Docker image
        run: eval `ssh-agent -s` && ssh-add ~/.ssh/id_rsa && DOCKER_BUILDKIT=1 docker build --build-arg ENV_FILE=.env -t ghcr.io/blendnet-ai/sakshm-frontend .

      - name: Push the Docker image to ghcr
        run: docker push ghcr.io/blendnet-ai/sakshm-frontend:latest
